### ISSUE TITLE
[JOSS review] Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by SunyongKwon** [qiangyicheng/flory#18]
Although "code_of_conduct.md" exists, contributing guidelines is rather unclear. Please, consider creating a `CONTRIBUTING.md` file (e.g. [https://contributing.md/example/](https://contributing.md/example/)).

**Comment by qiangyicheng** [comment]
Thank you for the comment and the suggestion for the `CONTRIBUTING.md` generator. We have added the `CONTRIBUTING.md` file. We choose to keep `CONTRIBUTING.md` brief and short to ease any contribution to the package.
